### PR TITLE
Use migration files with typescript

### PR DESCRIPTION
**Pull request by aggre**
# Description

It supports writing truffle's migration files with typescript.

# Why

For creating mockups, a larger migration file is required. So static type inspection is required.

This PR is related to #76.

---

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

### CODE REVIEW

**Comment by aggre** [comment]
I noticed the following.

This code is working:
```ts
artifacts.require('Lockup')
// And
deployer.deploy(...)
```

And this code is **not working**:
```ts
const { require: contract } = artifacts
contract('Lockup')
// And
const { deploy } = deployer
deploy(...)
```

Truffle objects seem cannot use the [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).

**Comment by Akira-Taniguchi** [comment]
I add other necessary contract to 2_prepare.ts.

I tried to execute command  (dev-protocol) and (dev-protocol mock), but don't work.

```
taniguchieinoMacBook-Pro:protocol taniguchiakira$ dev-protocol mock
-bash: dev-protocol: command not found
taniguchieinoMacBook-Pro:protocol taniguchiakira$ dev-protocol
-bash: dev-protocol: command not found
```

Do I need any other steps?

@aggre

**Comment by aggre** [comment]
The command is not usable in this project, the command is usable for a project on which it depends. e.g., dev-protocol/app

In this project, `npm run deploy mock` is working. @Akira-Taniguchi

**Comment by Akira-Taniguchi** [comment]
an error is occurd.
Do you have any idea?
I will continue the investigation.

```
taniguchieinoMacBook-Pro:protocol taniguchiakira$ npm run deploy mock

> @dev-protocol/protocol@0.1.0 predeploy /Users/taniguchiakira/frame00/protocol
> tsc -p tsconfig.migrations.json

types/truffle-contracts/index.d.ts:5:25 - error TS2307: Cannot find module 'bignumber.js'.

5 import {BigNumber} from "bignumber.js";
                          ~~~~~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @dev-protocol/protocol@0.1.0 predeploy: `tsc -p tsconfig.migrations.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @dev-protocol/protocol@0.1.0 predeploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taniguchiakira/.npm/_logs/2019-12-09T01_00_31_673Z-debug.log
```

@aggre

**Comment by aggre** [comment]
I added the bignumber.js to dependencies, so should you run `npm install` or `npm ci` command. @Akira-Taniguchi

**Comment by aggre** [comment]
In the future, I think better to have a mechanism that automatically resolves dependencies when dependencies are added. 🤔

**Comment by Akira-Taniguchi** [comment]
I resolve it.
I execute "npm install bignumber.js" command.

>I added the bignumber.js to dependencies, so should you run npm install or npm ci command.

That's right. I'm sorry.

**Comment by aggre** [comment]
I changed the build strategy, can build less configuration. No changed the codes.

**Comment by Akira-Taniguchi** [comment]
I confirmed that contract was deployed to mock network

```
3_mock.js
=========
mock
   -------------------------------------
   > Total cost:                   0 ETH


Summary
=======
> Total deployments:   18
> Final cost:          0.99654888 ETH

```

I will merge this request.

**Comment by Akira-Taniguchi** [comment]
↑
@aggre

**Pull request merged**
