### PR TITLE
Testing Withdraw Contract

### LINKED ISSUE #208: withdraw
# Description

create unit test of withdraw

### PR DESCRIPTION
**Pull request by aggre**
# Description

I implemented tests for Withdraw Contract.

And, I made some changes as follows:
- Deleted Allocator.withdraw and centralized it with Withdraw.withdraw.
- Splited Withdraw.calcurateWithdrawableAmount into two functions.
- Changed major `external` functions that users call directly, to `public` function.

# Why

Testing is needed.

# Related Issues

Fixes #208 .

---

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

### CODE REVIEW

**Comment by Akira-Taniguchi** [comment]
I have one question.

>Changed major external functions that users call directly, to public function.


Since the gas bill at the time of calling is less for external than for public, it is like that,
Is there any reason to change the inherited function, which is not called from within the same contract, from external to public?

(呼び出し時のガス代がpublicよりexternalの方が少なくなるのでそうしてい流のですが、
継承先、同一コントラクト内から呼ばれることのない関数をexternalからpublicに変更する理由は何かありますか？)

@aggre

**Comment by aggre** [comment]
my misunderstanding. Changed back to external.

However, `calculateWithdrawableAmount` function and `calculateAmount` function are called both inside and outside, so it is better to make them public for usability. I think it is inconvenient to not know the withdrawable amount until withdraw.

(external に戻しました! しかし `calculateWithdrawableAmount` と `calculateAmount` は private ではなく public がいいと思いました。外部からも呼び出せないと、出金するまで出金可能額が分からないことになり不便だからです )

**Comment by Akira-Taniguchi** [comment]
The test has encountered an error.

I'll check it now.

https://github.com/dev-protocol/protocol/pull/282/checks?check_run_id=399972497

@aggre

**Comment by aggre** [comment]
I fix bugs..

**Pull request merged**
