### PR TITLE
DIP7

### PR DESCRIPTION
**Pull request by aggre**
# Description

I implemented https://github.com/dev-protocol/DIPs/issues/7

# Why

https://github.com/dev-protocol/DIPs/issues/7

# Related Issues

https://github.com/dev-protocol/DIPs/issues/7

---

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

### CODE REVIEW

**Comment by Akira-Taniguchi** [comment]
There are two points that I've noticed.

・Why not remove the setBaseBlockNumber, getBaseBlockNumber, and getBaseBlockNumberKey methods from AllocatorStorage?
　・I'm pretty busy right now, so it doesn't really affect me, so we'll just leave it at that?

・Two tests are failing.
　・We'll see.

@aggre

**Comment by aggre** [comment]
> 　・I'm pretty busy right now, so it doesn't really affect me, so we'll just leave it at that?

yes, keep it just now.

> ・Two tests are failing.

oh... I'll check it!

**Comment by Akira-Taniguchi** [comment]
OK

**Comment by aggre** [comment]
I merge this

**Pull request merged**
