### PR TITLE
drop unnecessary contract

### PR DESCRIPTION
**Pull request by Akira-Taniguchi**
# Description

drop unnecessary contract

# Why

Product optimization

### CODE REVIEW

**Comment by aggre** [comment]
@Akira-Taniguchi Is `TestErc20Token.sol` file also unnecessary?

**Comment by Akira-Taniguchi** [comment]
@aggre I think so, 
I do n’t think it ’s necessary at least for now.
I will make it again if needed.

**Comment by aggre** [comment]
@Akira-Taniguchi All right, I deleted it and applied lint it.

**Comment by aggre** [comment]
I fix the conflict.

**Pull request merged**
