### PR TITLE
fix incriment bug

### PR DESCRIPTION
**Pull request by Akira-Taniguchi**
# Description

Withdrawable's price does not indicate correctly the withdrawable amount.

# Why

Details-> #42

### CODE REVIEW

**Comment by Akira-Taniguchi** [comment]
@aggre 
plwase wait, because I don't write test case yet.....

**Comment by Akira-Taniguchi** [comment]
Maybe this is helpful
https://www.trufflesuite.com/docs/truffle/testing/writing-tests-in-javascript

**Comment by Akira-Taniguchi** [comment]
Is there a deadline for this issue?

If you hurry, test cases will be added at a later date, so please review and merge.

@aggre

**Comment by aggre** [comment]
Thank you for your PR!

Testing is okay later. I merge it!

**Comment by aggre** [comment]
Fixes #42

**Pull request merged**
